# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mars_rover.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import os
import requests
import json
import shutil
import threading
import email_ui
count=0


class Ui_MainWindow(object):

    def email_window(self):
        self.window=QtWidgets.QWidget()
        self.ui=email_ui.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        self.index=1
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 860)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 251, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 100, 251, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 150, 251, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(8, "")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 20, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Syamala Ramana")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.fetchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.fetchbutton.setGeometry(QtCore.QRect(10, 200, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fetchbutton.setFont(font)
        self.fetchbutton.setObjectName("fetchbutton")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(10, 800, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.Nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Nextbutton.setGeometry(QtCore.QRect(410, 800, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Nextbutton.setFont(font)
        self.Nextbutton.setObjectName("Nextbutton")
        self.Sharebutton=QtWidgets.QPushButton(self.centralwidget)
        self.Sharebutton.setGeometry(QtCore.QRect(320,850,200,41))
        font=QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Sharebutton.setFont(font)
        self.Sharebutton.setObjectName("Sharebutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.fetchbutton.clicked.connect(self.threading)
        self.previous_button.clicked.connect(self.previous)
        self.Nextbutton.clicked.connect(self.next)
        self.Sharebutton.clicked.connect(self.email_window)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label = QLabel(MainWindow)
        self.label.move(50,600)

        self.label.setGeometry(2,250,800,535)
        # self.label.setScaledContents(True)
        self.label.setScaledContents(True)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Rover:"))
        self.label_2.setText(_translate("MainWindow", "Earth date:"))
        self.label_3.setText(_translate("MainWindow", "Camera:"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Curiosity"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "FHAZ"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "RHAZ"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "MAST"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "CHEMCAM"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "MAHLI"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "MARDI"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "NAVCAM"))
        self.label_4.setText(_translate("MainWindow", "MARS ROVER IMAGES"))
        self.fetchbutton.setText(_translate("MainWindow", "Fetch image"))
        self.previous_button.setText(_translate("MainWindow", "Previous image"))
        self.Nextbutton.setText(_translate("MainWindow", "Next image"))
        self.Sharebutton.setText(_translate("MainWindow", "Share it"))

    def press_it(self):
        global lst
        earth_date=self.dateEdit.date().toPyDate()
        demo_key=os.getenv("API_KEY")
        camera=self.comboBox_2.currentText().lower()
        lst=[]
        response=requests.get(f"https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?earth_date={earth_date}&camera={camera}&date&api_key={demo_key}")
        data = json.loads(response.text)
        pixmap = QPixmap("images/photo1.png").scaled(500,500)
        self.label.setPixmap(pixmap)
        self.label.show()

        
        count = 0
        for i in data['photos']:
            res = requests.get(i["img_src"],stream = True)
            lst.append(i["img_src"])
            print(i["img_src"])
            count+=1
            if count == 10:
                break
            else:
                with open(f"images/photo{count}.png",'wb') as f:
                    shutil.copyfileobj(res.raw,f)

    def previous(self):
        if self.index>1:
            self.index -= 1
            pixmap = QPixmap(f"images/photo{self.index}.png")
            self.label.setGeometry(2,250,1000,500)
            self.label.setPixmap(pixmap)
            self.label.show()
            print(self.index)

    def next(self):
        self.index += 1
        if self.index ==10:
            self.index -= 1
        pixmap = QPixmap(f"images/photo{self.index}.png")
        self.label.setGeometry(2,250,1000,500)
        self.label.setPixmap(pixmap)
        self.label.show()
        print(self.index)
    
        

    def threading(self):
        thread=threading.Thread(target=self.press_it)
        thread.start()   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.move(500,150)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
